### ISSUE TITLE
Strange behavior of normalize() with \t character

### ISSUE THREAD

**Issue by VladKha** [pudo/normality#11]
Observing strange behavior for this example:

```python
from normality import normalize

text = normalize('this \n\n\r\nhas\tlots of \nodd spacing.')
print(text)
# 'this haslots of odd spacing'
```

Notice how "has" and "lots" joined into a single word
Is it the expected behavior?

BTW, thank you for amazing work on the package!

**Comment by pudo** [comment]
I'm beginning to realise there might be limits to how the conversion works currently. It's using unicode character classes to determine what characters to remove or replace with space. `\t` is apparently a `Cc`, and some of the other `Cc`s want to be removed. Changing it to space now but maybe we need a specific per-character mapping in the long run after all :/
