### ISSUE TITLE
Undeclared dependency on charset normalizer?

### ISSUE THREAD

**Issue by gitonthescene** [pudo/normality#15]
Hi, I use normality for my project and the tests in the Dependabot pull request [failed](https://github.com/gitonthescene/csv-reconcile/runs/5496261260?check_suite_focus=true).  Does the dependency on charset_normalizer need to be added to a setup.py?

**Comment by gitonthescene** [comment]
Thanks.  Will there be a release with this change soon?

**Comment by pudo** [comment]
Yes sorry I hotfixed this after half a bottle of wine so no commentary, but there's 2.3.1 on PyPI now.

**Comment by gitonthescene** [comment]
Thanks.  I guess Dependabot will pick it up eventually.  I hadn't seen anything, so I was wondering.

**Comment by gitonthescene** [comment]
FWIW, Dependabot has caught up.  Thanks for the quick fix.
