### ISSUE TITLE
BOM_RE doesnt cover all BOMs

### ISSUE THREAD

**Issue by jayvdb** [pudo/normality#8]
The BOM_RE is only one of the many BOMs that are possible.  c.f. https://github.com/1441302031/luaGameFramework/blob/05a7a34a351c081efe76726d0f314a5e4bd4eefe/MyLuaGame/remove_bom.py

**Comment by jayvdb** [comment]
Actually it might, sorry.  I need to re-test.

**Comment by pudo** [comment]
Closing as this is a bit unclear.
